version: '3'

services:
  api01: &api
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - FasterNews
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  api02: 
    <<: *api
    ports:
      - "8081:8080"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
    ports:
      - "9999:9999"
    networks:
      - FasterNews

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - FasterNews

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123pass
      MYSQL_DATABASE: news
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 123pass
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - FasterNews

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:9000"
    networks:
      - FasterNews

networks:
  FasterNews: